cornershop-backend-test/backend_test/urls.py
from django.urls import include, path

from menus.views import home_view

from .utils.healthz import healthz

urlpatterns = [
    path("healthz", healthz, name="healthz"),
    path("", home_view, name="home"),
    path("menus/", include("menus.urls"), name="menus"),
    path("menu/", include("menu_selections.urls"), name="menuselections"),
    path("accounts/", include("django.contrib.auth.urls")),
]

cornershop-backend-test/menu_selections/urls.py
from django.urls import path

from .views import (
    MenuSelectionCreateView,
    MenuSelectionDetailView,
    TodaysMenuSelectionListView,
)

app_name = "menuselections"
urlpatterns = [
    path(
        "<uuid:uuid>/",
        MenuSelectionCreateView.as_view(),
        name="menuselection-create",
    ),
    path(
        "menuselection/today",
        TodaysMenuSelectionListView.as_view(),
        name="menuselection-todaylist",
    ),
    path(
        "menuselection/<int:id>",
        MenuSelectionDetailView.as_view(),
        name="menuselection-detail",
    ),
]

cornershop-backend-test/menus/urls.py
from django.urls import path

from menus.views import (
    MenuCreateView,
    MenuDetailView,
    MenuListView,
    MenuOptionCreateView,
    MenuOptionUpdateView,
    delete_menuoption_view,
    send_slack_message_view,
)

app_name = "menus"
urlpatterns = [
    path("all/", MenuListView.as_view(), name="menu-list"),
    path("create/", MenuCreateView.as_view(), name="menu-create"),
    path("<int:id>/", MenuDetailView.as_view(), name="menu-detail"),
    path(
        "menuoption/<int:id>/create/",
        MenuOptionCreateView.as_view(),
        name="menuoption-create",
    ),
    path(
        "menuoption/update/<int:id>/",
        MenuOptionUpdateView.as_view(),
        name="menuoption-update",
    ),
    path(
        "menuoption/delete/<int:id>/",
        delete_menuoption_view,
        name="menuoption-delete",
    ),
    path("slack/send/<uuid:uuid>/", send_slack_message_view, name="send-slack-message"),
]

cornershop-backend-test/templates/base.html
<!doctype html>
<html>
<style>
    .stick-to-right {
        width: 250px;
        float: right;
    }
</style>
<title>Cornershop Test</title>
<div>

    <head>
        <a class="nav-item nav-link" style="color:black" href="{% url 'home' %}"> Lunch System </a>
        {% if user.is_authenticated %}
        <a class="nav-item nav-link stick-to-right" href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a class="nav-item nav-link stick-to-right" href="{% url 'login' %}">Login</a>
        {% endif %}
    </head>
</div>

<body>
    {% block content %}
    {% endblock %}
</body>

</html>

cornershop-backend-test/templates/home.html
{% extends 'base.html' %}

{% block content %}
{% if request.user.is_authenticated %}
<h1>Welcome</h1>
{% if todays_menu %}
<button class="ml-2"> <a style="color:black" href="{% url 'menus:menu-detail' todays_menu.id %}">Update today's
                menu</a></button>
<div>
        <button class="ml-2"> <a class="ml-2" style="color:black"
                        href="{% url 'menus:send-slack-message' todays_menu.uuid %}">
                        Send slack message </a></button>
</div>
{% else %}
<div>
        <button class="ml-2"> <a class="ml-2" style="color:black" href="{% url 'menus:menu-create' %}"> Create a menu
                </a></button>
</div>
{% endif %}
<div>
        <button class="ml-2"> <a class="ml-2" style="color:black" href="{% url 'menus:menu-list' %}"> See past menus
                </a></button>
</div>
<div>
        <button class="ml-2"> <a class="ml-2" style="color:black"
                        href="{% url 'menuselections:menuselection-todaylist' %}">
                        See
                        today's menu selections </a></button>
</div>
{% else %}
<div>Are you Nora? <a class="nav-item nav-link" href="{% url 'login' %}">Login</a></div>
{% if todays_menu and can_still_order_by_time %}
<div>Are you an Employee? <a class="nav-item nav-link"
                href="{% url 'menuselections:menuselection-create' todays_menu.uuid %}">Select
                today's
                menus</a>
</div>
{% else %}
<div>Nothing to order here.</div>
{% endif %}



{% endif %}
{% endblock %}